faiss_db:
  collection_name: "elevenplus_vdb"


embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "deepseek-r1-distill-llama-70b"
    temperature: 0.7
    max_output_tokens: 8192

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0.7
    max_output_tokens: 8192

  openai:
    provider: "openai"
    model_name: "gpt-4"
    temperature: 0.7
    max_output_tokens: 8192
